[build]
  # The command to build the project
  command = "npm run build"
  
  # The directory to publish
  publish = "artifacts/portfolio/dist/public"


# Redirects for Single Page Application (SPA) routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
